import os
import time
import requests
from prompt_engine import ShariahAdvisorPromptManager
from shariah_filter import shariahfilter

class AIAgent:
    def __init__(self):
        groq_key = os.getenv("GROQ_API_KEY")
        openrouter_key = os.getenv("OPENROUTER_API_KEY")
        gemini_key = os.getenv("GEMINI_API_KEY")

        self.providers = []

        # 1. GROQ (Primary)
        if groq_key:
            self.providers.append({
                "name": "Groq",
                "url": "https://api.groq.com/openai/v1/chat/completions",
                "headers": {"Authorization": f"Bearer {groq_key}", "Content-Type": "application/json"},
                "model": "llama-3.3-70b-versatile" 
            })

        # 2. OPENROUTER: GROK
        if openrouter_key:
            self.providers.append({
                "name": "Grok (OpenRouter)",
                "url": "https://openrouter.ai/api/v1/chat/completions",
                "headers": {"Authorization": f"Bearer {openrouter_key}", "Content-Type": "application/json"},
                "model": "xai/grok-2-1212"
            })

        # 3. OPENROUTER: QWEN
        if openrouter_key:
            self.providers.append({
                "name": "Qwen 3.6 (OpenRouter)",
                "url": "https://openrouter.ai/api/v1/chat/completions",
                "headers": {"Authorization": f"Bearer {openrouter_key}", "Content-Type": "application/json"},
                "model": "qwen/qwen-max"
            })

        # 4. GOOGLE AI STUDIO: GEMINI
        if gemini_key:
            self.providers.append({
                "name": "Gemini 2.5 Flash (Google AI Studio)",
                "url": "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
                "headers": {"Authorization": f"Bearer {gemini_key}", "Content-Type": "application/json"},
                "model": "gemini-2.5-flash"
            })

        if not self.providers:
            print("🚨 WARNING: No AI API keys found in .env! The AI Agent will fail.")

        self.prompt_engine = ShariahAdvisorPromptManager()
        self.shariah = shariahfilter()

    # Add page_context to the process parameters
    # Add preferences to the parameters
    def process(self, user_input: str, ticker: str = None, chat_history: list = None, page_context: str = "Unknown", preferences: dict = None):
        
        # 1. Pass preferences into the prompt engine!
        system_prompt = self.prompt_engine.get_system_prompt(preferences)

        is_compliant = False
        reason = "No specific stock analyzed."
        
        if ticker:
            compliance_data = self.shariah.check_compliance(ticker)
            is_compliant = compliance_data.get("isHalal", False)
            reason = compliance_data.get("reason", "Unknown")

        quantitative = {
            "is_compliant": is_compliant, 
            "reason": reason
        }

        # 2. Use the new format_agent_input method from prompt_engine
        prompt_content = self.prompt_engine.format_agent_input(user_input, quantitative, page_context)

        return self.build_final_response(
            system_prompt, 
            prompt_content, 
            chat_history,
            quantitative
        )

    def build_final_response(self, system_prompt, prompt_content, chat_history, shariah_result):
        
        messages = [{"role": "system", "content": system_prompt}]
        
        if chat_history:
            for msg in chat_history[-6:]:
                role = "assistant" if msg["role"] == "ai" else "user"
                messages.append({"role": role, "content": msg["content"]})
        
        messages.append({"role": "user", "content": prompt_content})
        
        errors = []
        
        for provider in self.providers:
            try:
                print(f"🌐 [AIAgent] Routing raw HTTP request to: {provider['name']}...")
                
                payload = {
                    "model": provider["model"],
                    "messages": messages, 
                    "temperature": 0.2
                }
                
                response = requests.post(provider["url"], headers=provider["headers"], json=payload, timeout=20)
                response.raise_for_status()
                
                data = response.json()
                final_advice = data["choices"][0]["message"]["content"]
                
                print(f"✅ [AIAgent] Success! Response generated by {provider['name']}")

                return {
                    "status": "SUCCESS",
                    "final_advice": final_advice, 
                    "raw_data": {                 
                        "shariah_status": shariah_result
                    }
                }
                
            except Exception as e:
                err_msg = f"{provider['name']} failed: {str(e)}"
                print(f"❌ [AIAgent] {err_msg}")
                errors.append(err_msg)
                import time
                time.sleep(1)

        return {
            "status": "ERROR",
            "final_advice": "I am currently experiencing high network traffic across all my cloud providers. Please try again in a few moments.",
            "error_details": errors
        }